### ISSUE TITLE
can't install flaskbb on my local machine

### ISSUE THREAD

**Issue by luofeiyu** [MongoEngine/flask-mongoengine#133]
I have installed many  things as http://www.flaskbb.org/first_steps.html   step by step.
when input python manage.py createall

/home/test/flaskbb/flaskbb# python manage.py createall

Traceback (most recent call last):
  File "manage.py", line 44, in <module>
    app = create_app(Config)
  File "/home/debian/flaskbb/flaskbb/flaskbb/app.py", line 63, in create_app
    configure_extensions(app)
  File "/home/debian/flaskbb/flaskbb/flaskbb/app.py", line 141, in configure_extensions
    babel.init_app(app=app, default_domain=FlaskBBDomain(app))
TypeError: init_app() got an unexpected keyword argument 'default_domain'

**Comment by syndbg** [comment]
Hey @luofeiyu , I'm not entirely sure how this is related to flask-mongoengine. Could you elaborate?
