### ISSUE TITLE
AttributeError: _initialised while creating a db.Document

### ISSUE THREAD

**Issue by tjadanel** [MongoEngine/flask-mongoengine#156]
Hello,

So i am using mongoengine to drive the mongodb of my flask app. When i pass values to the init of the db.Document object User it throws this error. is this a bug?

```
Traceback (most recent call last):
  File "/home/dev/.virtualenvs/app_env/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/dev/.virtualenvs/app_env/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/home/dev/.virtualenvs/app_env/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/dev/.virtualenvs/app_env/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/dev/.virtualenvs/app_env/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/dev/.virtualenvs/app_env/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/dev/.virtualenvs/app_env/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/dev/.virtualenvs/app_env/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/dev/Projects/app_flask/app/auth_blueprint/views.py", line 75, in register
    password = str(password)
  File "/home/dev/Projects/app_flask/app/auth_blueprint/models.py", line 41, in __init__
    self.email = email
  File "/home/dev/.virtualenvs/app_env/lib/python2.7/site-packages/mongoengine/base/document.py", line 188, in __setattr__
    super(BaseDocument, self).__setattr__(name, value)
  File "/home/dev/.virtualenvs/app_env/lib/python2.7/site-packages/mongoengine/base/fields.py", line 125, in __set__
    if instance._initialised:
AttributeError: _initialised
```

My models.py

```
class User(UserMixin, db.Document):
	created_at = db.DateTimeField(
        default=datetime.datetime.now, required=True
	)
	email = db.EmailField(unique=True,required=True)
	pwdhash = db.StringField(required=True, max_length=50)
	active = db.BooleanField(default=True, required=False)
	isAdmin = db.BooleanField(default=False, required=False)

	def is_active(self):
		return True

	def is_anonymous(self):
		return False

	def is_authenticated(self):
		return True

	def get_id(self):
		return unicode(self.id)

	def check_password(self, password):
		return check_password_hash(self.pwdhash, password)

	def __repr__(self):
		return '<User %r>' % self.id
    
   	def __init__(self, email, password):
		self.email = email
		print self.email
		self.pwdhash = generate_password_hash(password)
		print self.pwdhash

	meta = {
        'allow_inheritance': True,
        'indexes': ['-created_at', 'email'],
        'ordering' : ['-created_at']
    }
```

my views.py segment calling the User object

```
user = User( email = email, password = password)
user.save()
print "user saved"
```

**Comment by luckenbach** [comment]
As no one response to this and some one else might happen upon this issue like I did.

The fix for me is super'ing the class before you start settings stuff
```python
super(db.Document, self).__init__(*args, **kwargs)
```

**Comment by losintikfos** [comment]
I will close this issue as resolved unless confirmed otherwise.
