### ISSUE TITLE
Version 0.7.3 error on python 2.6

### ISSUE THREAD

**Issue by dpgaspar** [MongoEngine/flask-mongoengine#176]
I get this errors on my tests.

======================================================================
ERROR: Failure: SyntaxError (invalid syntax (__init__.py, line 77))
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/nose/loader.py", line 414, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/travis/build/dpgaspar/Flask-AppBuilder/flask_appbuilder/tests/test_mongoengine.py", line 7, in <module>
    from flask_mongoengine import MongoEngine
  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/flask_mongoengine/__init__.py", line 77
    conn = {k.lower(): v for k, v in conn_settings.items() if v is not None}
                           ^
SyntaxError: invalid syntax

**Comment by losintikfos** [comment]
This issue has been fixed in the current version of master.

**Comment by dpgaspar** [comment]
Great, Thanks!
