### ISSUE TITLE
Install fails with pip install because of ''coverage" not found

### ISSUE THREAD

**Issue by wooclary** [MongoEngine/flask-mongoengine#190]
I am using Python3.4.3, win-64 and execute following comand for install:

    pip install flask-mongoengine

and i got an error:

    Collecting flask-mongoengine
      Using cached flask-mongoengine-0.7.4.tar.gz
        Complete output from command python setup.py egg_info:
        E:\Anaconda3\lib\site-packages\setuptools-14.3-py3.4.egg\pkg_resources\__init__.py:2512: 
    PEP440Warning: 'llvmlite (0.2.2-1-gbcb15be)' is being parsed as a legacy, non PEP 440, version. 
    You may find odd behavior and sort order. In particular it will be sorted as less than 0.0. It is recommend to migrate to PEP 440 compatible versions.
        Download error on https://pypi.python.org/simple/coverage/: [WinError 10054] 远程主机强迫关闭了一个现有的连接。 -- Some packages may not be found!
        Couldn't find index page for 'coverage' (maybe misspelled?)
        Download error on https://pypi.python.org/simple/: [WinError 10054] 远程主机强迫关闭了一个现有的连接。 -- Some packages may not be found!
        No local packages or download links found for coverage
        Traceback (most recent call last):
          File "<string>", line 20, in <module>
          File "C:\Users\Shawn\AppData\Local\Temp\pip-build-xqcn2ua_\flask-mongoengine\setup.py", line 79, in <module>
            'Topic :: Software Development :: Libraries :: Python Modules'
          File "E:\Anaconda3\lib\distutils\core.py", line 108, in setup
            _setup_distribution = dist = klass(attrs)
          File "E:\Anaconda3\lib\site-packages\setuptools-14.3-py3.4.egg\setuptools\dist.py", line 265, in __init__
          File "E:\Anaconda3\lib\site-packages\setuptools-14.3-py3.4.egg\setuptools\dist.py", line 310, in fetch_build_eggs
          File "E:\Anaconda3\lib\site-packages\setuptools-14.3-py3.4.egg\pkg_resources\__init__.py", line 799, in resolve
          File "E:\Anaconda3\lib\site-packages\setuptools-14.3-py3.4.egg\pkg_resources\__init__.py", line 1049, in best_match
          File "E:\Anaconda3\lib\site-packages\setuptools-14.3-py3.4.egg\pkg_resources\__init__.py", line 1061, in obtain
          File "E:\Anaconda3\lib\site-packages\setuptools-14.3-py3.4.egg\setuptools\dist.py", line 377, in fetch_build_egg
         File "E:\Anaconda3\lib\site-packages\setuptools-14.3-py3.4.egg\setuptools\command\easy_install.py", line 623, in easy_install
    distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('coverage')

**Comment by wooclary** [comment]
I use chinese windows10 os, and the

    远程主机强迫关闭了一个现有的连接。

means that the remote host close the connection.

**Comment by losintikfos** [comment]
Thanks for reporting this.

**Comment by losintikfos** [comment]
Remote host connection issue is pypi connection related not flask-mongoengine.
