### ISSUE TITLE
KeyError accessing connection property from the shell

### ISSUE THREAD

**Issue by josepanguera** [MongoEngine/flask-mongoengine#232]
Using the integrated shell command http://flask.pocoo.org/docs/0.11/cli/#running-a-shell when trying to access the `connection`:

    $ flask shell
    >>> from project import db
    >>> db.connection
    Traceback (most recent call last):
      File "<console>", line 1, in <module>
      File "/.../local/lib/python2.7/site-packages/flask_mongoengine/__init__.py", line 149, in connection
        return current_app.extensions['mongoengine'][self]['conn']
    KeyError: <flask_mongoengine.MongoEngine object at 0x7f7c1f5b7ed0>

This can be solved (I've try it locally) saving a reference to the app when initialising MongoEngine, but in this commit https://github.com/MongoEngine/flask-mongoengine/commit/c3716150d2ed1c04c30842e0e3664f8068ec7149 is mentioned that this is dangerous.

FWIW in Flask-Sqlalchemy a reference to the app is used: https://github.com/mitsuhiko/flask-sqlalchemy/blob/2.1/flask_sqlalchemy/__init__.py#L912

I've also tried to solve it using the app context stack (see [1](http://flask.pocoo.org/docs/0.11/extensiondev/#the-extension-code) [2](https://github.com/mitsuhiko/flask-sqlalchemy/blob/2.1/flask_sqlalchemy/__init__.py#L39) [3](https://github.com/mitsuhiko/flask-sqlalchemy/blob/2.1/flask_sqlalchemy/__init__.py#L49) and [4](https://github.com/mitsuhiko/flask-sqlalchemy/blob/2.1/flask_sqlalchemy/__init__.py#L919)) and it also fails with `KeyError`

**Comment by josepanguera** [comment]
This is fixed by installing Flask 0.11.1 .

I believe this pull request https://github.com/pallets/flask/pull/1872 is what fixed it.
