### ISSUE TITLE
connect with MONGODB_SETTINGS in url styles is not working in ubuntu but window does

### ISSUE THREAD

**Issue by woosungchu** [MongoEngine/flask-mongoengine#260]
This error was similar with #274 . 
Debugged at 0.8.1

###my code
MONGODB_SETTINGS = {
        'db':'dev',
        'host': os.environ.get('DB_DEV_URI')
}

###os.environment variable ## 
DB_DEV_URI : 'mongodb://<---id-->:<----pw--->@ds027425.mlab.com:27425/heroku_mr51rc25'
pymongo.errors.ServerSelectionTimeoutError

pymongo.errors.ServerSelectionTimeoutError: heroku_mr51rc25:27017: [Errno -2] Name or service not known
Traceback (most recent call last)

    File "/home/woosungchu/git/heroku-resume/env/lib/python3.5/site-packages/flask/app.py", line 1836, in __call__

    return self.wsgi_app(environ, start_response)

    File "/home/woosungchu/git/heroku-resume/env/lib/python3.5/site-packages/flask/app.py", line 1820, in wsgi_app

    response = self.make_response(self.handle_exception(e))

    File "/home/woosungchu/git/heroku-resume/env/lib/python3.5/site-packages/flask/app.py", line 1403, in handle_exception

    reraise(exc_type, exc_value, tb)

    File "/home/woosungchu/git/heroku-resume/env/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise

    raise value

    File "/home/woosungchu/git/heroku-resume/env/lib/python3.5/site-packages/flask/app.py", line 1817, in wsgi_app

    response = self.full_dispatch_request()

    File "/home/woosungchu/git/heroku-resume/env/lib/python3.5/site-packages/flask/app.py", line 1477, in full_dispatch_request

    rv = self.handle_user_exception(e)

    File "/home/woosungchu/git/heroku-resume/env/lib/python3.5/site-packages/flask/app.py", line 1381, in handle_user_exception

    reraise(exc_type, exc_value, tb)

    File "/home/woosungchu/git/heroku-resume/env/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise

    raise value

    File "/home/woosungchu/git/heroku-resume/env/lib/python3.5/site-packages/flask/app.py", line 1475, in full_dispatch_request

    rv = self.dispatch_request()

    File "/home/woosungchu/git/heroku-resume/env/lib/python3.5/site-packages/flask/app.py", line 1461, in dispatch_request

    return self.view_functions[rule.endpoint](**req.view_args)

    File "/home/woosungchu/git/heroku-resume/env/lib/python3.5/site-packages/flask/views.py", line 84, in view

    return self.dispatch_request(*args, **kwargs)

    File "/home/woosungchu/git/heroku-resume/env/lib/python3.5/site-packages/flask/views.py", line 149, in dispatch_request

    return meth(*args, **kwargs)

    File "/home/woosungchu/git/heroku-resume/resume/tumblelog/views.py", line 27, in get

    context = self.get_context()

    File "/home/woosungchu/git/heroku-resume/resume/tumblelog/views.py", line 15, in get_context

    posts = Post.objects.all()

    File "/home/woosungchu/git/heroku-resume/env/lib/python3.5/site-packages/mongoengine/queryset/manager.py", line 37, in __get__

    queryset = queryset_class(owner, owner._get_collection())

    File "/home/woosungchu/git/heroku-resume/env/lib/python3.5/site-packages/mongoengine/document.py", line 209, in _get_collection

    cls.ensure_indexes()

    File "/home/woosungchu/git/heroku-resume/env/lib/python3.5/site-packages/mongoengine/document.py", line 765, in ensure_indexes

    collection.create_index(fields, background=background, **opts)

    File "/home/woosungchu/git/heroku-resume/env/lib/python3.5/site-packages/pymongo/collection.py", line 1387, in create_index

    self.__create_index(keys, kwargs)

    File "/home/woosungchu/git/heroku-resume/env/lib/python3.5/site-packages/pymongo/collection.py", line 1294, in __create_index

    with self._socket_for_writes() as sock_info:

    File "/usr/lib/python3.5/contextlib.py", line 59, in __enter__

    return next(self.gen)

    File "/home/woosungchu/git/heroku-resume/env/lib/python3.5/site-packages/pymongo/mongo_client.py", line 762, in _get_socket

    server = self._get_topology().select_server(selector)

    File "/home/woosungchu/git/heroku-resume/env/lib/python3.5/site-packages/pymongo/topology.py", line 210, in select_server

    address))

    File "/home/woosungchu/git/heroku-resume/env/lib/python3.5/site-packages/pymongo/topology.py", line 186, in select_servers

     [Open an interactive python shell in this frame] self._error_message(selector))

**Comment by woosungchu** [comment]
I tried to figure out the difference point between window and ubuntu for two days but .....nothing..

**Comment by woosungchu** [comment]
similar with #247
