### ISSUE TITLE
Can not install 

### ISSUE THREAD

**Issue by keithsun80** [MongoEngine/flask-mongoengine#272]
python setup.py install
zip_safe flag not set; analyzing archive contents...
rednose: module references __file__
test_files.new_tests: module references __path__

▽
Installed /home/www/tmp/flask-mongoengine/rednose-1.2.1-py2.7.egg

▽
Searching for nose
Reading https://pypi.python.org/simple/nose/
Best match: nose 1.3.7
Downloading https://pypi.python.org/packages/58/a5/0dc93c3ec33f4e281849523a5a913fa1eea9a3068acfa754d44d88107a44/nose-1.3.7.tar.gz#md5=4d3ad0ff07b61373d2cefc89c5d0b20b
^CTraceback (most recent call last):
  File "setup.py", line 78, in <module>
    'Topic :: Software Development :: Libraries :: Python Modules'
  File "/usr/lib/python2.7/distutils/core.py", line 111, in setup
    _setup_distribution = dist = klass(attrs)
  File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 239, in __init__
    self.fetch_build_eggs(attrs.pop('setup_requires'))
  File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 264, in fetch_build_eggs
    replace_conflicting=True
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 620, in resolve
    dist = best[req.key] = env.best_match(req, ws, installer)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 858, in best_match
    return self.obtain(req, installer) # try and download/install
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 870, in obtain
    return installer(requirement)
  File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 314, in fetch_build_egg
    return cmd.easy_install(req)

pip install and python setup.py install

take a long time not finish.

**Comment by wojcikstefan** [comment]
This looks like a temporary issue with PyPI where `nose` couldn't be downloaded. Nothing to do with this repo's code. @lafrech I think this can be closed.
