### ISSUE TITLE
Error when used with the last version of mongoengine.

### ISSUE THREAD

**Issue by TimotheeJeannin** [MongoEngine/flask-mongoengine#291]
When used with `mongoengine` version `0.11.0` I get this error:

    Traceback (most recent call last):
      File "/usr/local/lib/python3.5/threading.py", line 914, in _bootstrap_inner
        self.run()
      File "/usr/local/lib/python3.5/threading.py", line 862, in run
        self._target(*self._args, **self._kwargs)
      File "/usr/local/lib/python3.5/site-packages/flask_socketio/cli.py", line 50, in run_server
        app = info.load_app()
      File "/usr/local/lib/python3.5/site-packages/flask/cli.py", line 209, in load_app
        rv = locate_app(self.app_import_path)
      File "/usr/local/lib/python3.5/site-packages/flask/cli.py", line 89, in locate_app
        __import__(module)
      File "/app/application/main.py", line 2, in <module>
        from .bootstrap import init_app
      File "/app/application/bootstrap.py", line 7, in <module>
        from flask_mongoengine import MongoEngine
      File "/usr/local/lib/python3.5/site-packages/flask_mongoengine/__init__.py", line 10, in <module>
        from mongoengine.base import ValidationError
    ImportError: cannot import name 'ValidationError'

From the `setup.py` file I can see that recent versions of `mongoengine` are allowed. 

Either change the requirements in the `setup.py` file or support both recent and older version ?

**Comment by TimotheeJeannin** [comment]
My mistake, already fixed in version 0.9.
