### ISSUE TITLE
help connecting to mlab database

### ISSUE THREAD

**Issue by hackydunk** [MongoEngine/flask-mongoengine#344]
While trying to connect to my mongodb mlab account I get the following error...

```Traceback (most recent call last):
  File "C:\Users\Admin\PycharmProjects\partygo\venv\lib\site-packages\flask\app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\Admin\PycharmProjects\partygo\venv\lib\site-packages\flask\app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Users\Admin\PycharmProjects\partygo\venv\lib\site-packages\flask\app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Admin\PycharmProjects\partygo\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Users\Admin\PycharmProjects\partygo\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Admin\PycharmProjects\partygo\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Admin\PycharmProjects\partygo\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Admin\PycharmProjects\partygo\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Users\Admin\PycharmProjects\partygo\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Admin\PycharmProjects\partygo\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Admin\PycharmProjects\partygo\user\views.py", line 11, in login
    user.save()
  File "C:\Users\Admin\PycharmProjects\partygo\venv\lib\site-packages\mongoengine\document.py", line 373, in save
    self.ensure_indexes()
  File "C:\Users\Admin\PycharmProjects\partygo\venv\lib\site-packages\mongoengine\document.py", line 856, in ensure_indexes
    collection = cls._get_collection()
  File "C:\Users\Admin\PycharmProjects\partygo\venv\lib\site-packages\mongoengine\document.py", line 190, in _get_collection
    db = cls._get_db()
  File "C:\Users\Admin\PycharmProjects\partygo\venv\lib\site-packages\mongoengine\document.py", line 179, in _get_db
    return get_db(cls._meta.get('db_alias', DEFAULT_CONNECTION_NAME))
  File "C:\Users\Admin\PycharmProjects\partygo\venv\lib\site-packages\mongoengine\connection.py", line 236, in get_db
    db.authenticate(conn_settings['username'], conn_settings['password'], **auth_kwargs)
  File "C:\Users\Admin\PycharmProjects\partygo\venv\lib\site-packages\pymongo\database.py", line 1274, in authenticate
    connect=True)
  File "C:\Users\Admin\PycharmProjects\partygo\venv\lib\site-packages\pymongo\mongo_client.py", line 614, in _cache_credentials

    sock_info.authenticate(credentials)
  File "C:\Users\Admin\PycharmProjects\partygo\venv\lib\site-packages\pymongo\pool.py", line 688, in authenticate
    auth.authenticate(credentials, self)
  File "C:\Users\Admin\PycharmProjects\partygo\venv\lib\site-packages\pymongo\auth.py", line 563, in authenticate
    auth_func(credentials, sock_info)
  File "C:\Users\Admin\PycharmProjects\partygo\venv\lib\site-packages\pymongo\auth.py", line 540, in _authenticate_default
    return _authenticate_scram(credentials, sock_info, 'SCRAM-SHA-1')
  File "C:\Users\Admin\PycharmProjects\partygo\venv\lib\site-packages\pymongo\auth.py", line 262, in _authenticate_scram
    res = sock_info.command(source, cmd)
  File "C:\Users\Admin\PycharmProjects\partygo\venv\lib\site-packages\pymongo\pool.py", line 579, in command
    unacknowledged=unacknowledged)
  File "C:\Users\Admin\PycharmProjects\partygo\venv\lib\site-packages\pymongo\network.py", line 150, in command
    parse_write_concern_error=parse_write_concern_error)
  File "C:\Users\Admin\PycharmProjects\partygo\venv\lib\site-packages\pymongo\helpers.py", line 155, in _check_command_response

    raise OperationFailure(msg % errmsg, code, response)
pymongo.errors.OperationFailure: Authentication failed.
```

my **config.py** file has the following information

```
MONGO_DB = 'XXXXXX'
MONGODB_HOST = 'XXXXXXXXXXX'
MONGODB_PORT = XXXXX
MONGODB_USERNAME = 'XXXXXXXXXX'
MONGODB_PASSWORD = 'XXXXXXXXXX'
```

**application.py** where I create the db

```
from flask import Flask
from flask_mongoengine import MongoEngine


db = MongoEngine()


def create_app(config=None):
    app = Flask(__name__)
    if config is not None:
        app.config.from_object(config)

    db.init_app(app)

    @app.route('/')
    def hello():
        return 'Hello World!'

    from user.views import user_page
    app.register_blueprint(user_page, url_prefix='/user')

    return app
```

help!!!

**Comment by hackydunk** [comment]
wrong variable name for MONGO_DB

Should be MONGODB_DB

**Comment by rajdeepbharati** [comment]
@hackydunk what is the `MONGODB_DB` variable? I'm also having trouble connecting to dlab using flask-mongoengine. Can you tell me the best way to do so?
