### ISSUE TITLE
I tried installing mongoengine on windows 10.

### ISSUE THREAD

**Issue by brainox** [MongoEngine/flask-mongoengine#403]
Collecting flask-mongoengine
  Using cached flask-mongoengine-0.9.5.tar.gz (111 kB)
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\mcmartins\desktop\enrollment\venv\scripts\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\McMartins\\AppData\\Local\\Temp\\pip-install-pxw7xcdx\\flask-mongoengine\\setup.py'"'"'; __file__='"'"'C:\\Users\\McMartins\\AppData\\Local\\Temp\\pip-install-pxw7xcdx\\flask-mongoengine\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\McMartins\AppData\Local\Temp\pip-pip-egg-info-u2l4se7g' 
         cwd: C:\Users\McMartins\AppData\Local\Temp\pip-install-pxw7xcdx\flask-mongoengine\
    Complete output (164 lines):
    Traceback (most recent call last):
      File "C:\Users\McMartins\AppData\Local\Programs\Python\Python38-32\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "C:\Users\McMartins\AppData\Local\Programs\Python\Python38-32\lib\distutils\dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "C:\Users\McMartins\AppData\Local\Programs\Python\Python38-32\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "c:\users\mcmartins\desktop\enrollment\venv\lib\site-packages\setuptools\command\bdist_egg.py", line 172, in run
        cmd = self.call_command('install_lib', warn_dir=0)
      File "c:\users\mcmartins\desktop\enrollment\venv\lib\site-packages\setuptools\command\bdist_egg.py", line 158, in call_command
        self.run_command(cmdname)
      File "C:\Users\McMartins\AppData\Local\Programs\Python\Python38-32\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "C:\Users\McMartins\AppData\Local\Programs\Python\Python38-32\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "c:\users\mcmartins\desktop\enrollment\venv\lib\site-packages\setuptools\command\install_lib.py", line 11, in run
        self.build()
      File "C:\Users\McMartins\AppData\Local\Programs\Python\Python38-32\lib\distutils\command\install_lib.py", line 105, in build
        self.run_command('build_py')
      File "C:\Users\McMartins\AppData\Local\Programs\Python\Python38-32\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "C:\Users\McMartins\AppData\Local\Programs\Python\Python38-32\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "c:\users\mcmartins\desktop\enrollment\venv\lib\site-packages\setuptools\command\build_py.py", line 49, in run
        self.build_modules()
      File "C:\Users\McMartins\AppData\Local\Programs\Python\Python38-32\lib\distutils\command\build_py.py", line 352, in build_modules
        self.build_module(module, module_file, package)
      File "c:\users\mcmartins\desktop\enrollment\venv\lib\site-packages\setuptools\command\build_py.py", line 74, in build_module
        outfile, copied = orig.build_py.build_module(self, module, module_file,      
      File "C:\Users\McMartins\AppData\Local\Programs\Python\Python38-32\lib\distutils\command\build_py.py", line 342, in build_module
        self.mkpath(dir)
      File "C:\Users\McMartins\AppData\Local\Programs\Python\Python38-32\lib\distutils\cmd.py", line 338, in mkpath
        dir_util.mkpath(name, mode, dry_run=self.dry_run)
      File "C:\Users\McMartins\AppData\Local\Programs\Python\Python38-32\lib\distutils\dir_util.py", line 70, in mkpath
        os.mkdir(head, mode)
      File "c:\users\mcmartins\desktop\enrollment\venv\lib\site-packages\setuptools\sandbox.py", line 310, in wrap
        path = self._remap_input(name, path, *args, **kw)
      File "c:\users\mcmartins\desktop\enrollment\venv\lib\site-packages\setuptools\sandbox.py", line 452, in _remap_input
        self._violation(operation, os.path.realpath(path), *args, **kw)
      File "c:\users\mcmartins\desktop\enrollment\venv\lib\site-packages\setuptools\sandbox.py", line 407, in _violation
        raise SandboxViolation(operation, args, kw)
    setuptools.sandbox.SandboxViolation: SandboxViolation: mkdir('C:\\Users\\MCMART~1\\AppData\\Local\\Temp\\easy_install-pd3xglu5\\rednose-1.3.0\\build', 511) {}        

    The package setup script has attempted to modify files on your system
    that are not within the EasyInstall build area, and has been aborted.

    This package cannot be safely installed by EasyInstall, and may not
    support alternate installation locations even if you run its setup
    script by hand.  Please inform the package's author and the EasyInstall
    maintainers to find out if a fix or workaround is available.

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "c:\users\mcmartins\desktop\enrollment\venv\lib\site-packages\setuptools\sandbox.py", line 154, in save_modules
        yield saved
      File "c:\users\mcmartins\desktop\enrollment\venv\lib\site-packages\setuptools\sandbox.py", line 195, in setup_context
        yield
      File "c:\users\mcmartins\desktop\enrollment\venv\lib\site-packages\setuptools\sandbox.py", line 250, in run_setup
        _execfile(setup_script, ns)
      File "c:\users\mcmartins\desktop\enrollment\venv\lib\site-packages\setuptools\sandbox.py", line 45, in _execfile
        exec(code, globals, locals)
      File "C:\Users\MCMART~1\AppData\Local\Temp\easy_install-pd3xglu5\rednose-1.3.0\setup.py", line 11, in <module>
        long_description = io.open(doc_path, encoding='utf-8').read()
      File "c:\users\mcmartins\desktop\enrollment\venv\lib\site-packages\setuptools\__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "C:\Users\McMartins\AppData\Local\Programs\Python\Python38-32\lib\distutils\core.py", line 163, in setup
        raise SystemExit("error: " + str(msg))
    SystemExit: error: SandboxViolation: mkdir('C:\\Users\\MCMART~1\\AppData\\Local\\Temp\\easy_install-pd3xglu5\\rednose-1.3.0\\build', 511) {}

    The package setup script has attempted to modify files on your system
    that are not within the EasyInstall build area, and has been aborted.

    This package cannot be safely installed by EasyInstall, and may not
    support alternate installation locations even if you run its setup
    script by hand.  Please inform the package's author and the EasyInstall
    maintainers to find out if a fix or workaround is available.

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "c:\users\mcmartins\desktop\enrollment\venv\lib\site-packages\setuptools\command\easy_install.py", line 1144, in run_setup
        run_setup(setup_script, args)
      File "c:\users\mcmartins\desktop\enrollment\venv\lib\site-packages\setuptools\sandbox.py", line 253, in run_setup
        raise
      File "C:\Users\McMartins\AppData\Local\Programs\Python\Python38-32\lib\contextlib.py", line 131, in __exit__
        self.gen.throw(type, value, traceback)
      File "c:\users\mcmartins\desktop\enrollment\venv\lib\site-packages\setuptools\sandbox.py", line 195, in setup_context
        yield
      File "C:\Users\McMartins\AppData\Local\Programs\Python\Python38-32\lib\contextlib.py", line 131, in __exit__
        self.gen.throw(type, value, traceback)
      File "c:\users\mcmartins\desktop\enrollment\venv\lib\site-packages\setuptools\sandbox.py", line 166, in save_modules
        saved_exc.resume()
      File "c:\users\mcmartins\desktop\enrollment\venv\lib\site-packages\setuptools\sandbox.py", line 141, in resume
        six.reraise(type, exc, self._tb)
      File "c:\users\mcmartins\desktop\enrollment\venv\lib\site-packages\setuptools\_vendor\six.py", line 685, in reraise
        raise value.with_traceback(tb)
      File "c:\users\mcmartins\desktop\enrollment\venv\lib\site-packages\setuptools\sandbox.py", line 154, in save_modules
        yield saved
      File "c:\users\mcmartins\desktop\enrollment\venv\lib\site-packages\setuptools\sandbox.py", line 195, in setup_context
        yield
      File "c:\users\mcmartins\desktop\enrollment\venv\lib\site-packages\setuptools\sandbox.py", line 250, in run_setup
        _execfile(setup_script, ns)
      File "c:\users\mcmartins\desktop\enrollment\venv\lib\site-packages\setuptools\sandbox.py", line 45, in _execfile
        exec(code, globals, locals)
      File "C:\Users\MCMART~1\AppData\Local\Temp\easy_install-pd3xglu5\rednose-1.3.0\setup.py", line 11, in <module>
        long_description = io.open(doc_path, encoding='utf-8').read()
      File "c:\users\mcmartins\desktop\enrollment\venv\lib\site-packages\setuptools\__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "C:\Users\McMartins\AppData\Local\Programs\Python\Python38-32\lib\distutils\core.py", line 163, in setup
        raise SystemExit("error: " + str(msg))
    SystemExit: error: SandboxViolation: mkdir('C:\\Users\\MCMART~1\\AppData\\Local\\Temp\\easy_install-pd3xglu5\\rednose-1.3.0\\build', 511) {}

    The package setup script has attempted to modify files on your system
    that are not within the EasyInstall build area, and has been aborted.

    This package cannot be safely installed by EasyInstall, and may not
    support alternate installation locations even if you run its setup
    script by hand.  Please inform the package's author and the EasyInstall
    maintainers to find out if a fix or workaround is available.

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\McMartins\AppData\Local\Temp\pip-install-pxw7xcdx\flask-mongoengine\setup.py", line 36, in <module>
        setup(
      File "c:\users\mcmartins\desktop\enrollment\venv\lib\site-packages\setuptools\__init__.py", line 144, in setup
        _install_setup_requires(attrs)
      File "c:\users\mcmartins\desktop\enrollment\venv\lib\site-packages\setuptools\__init__.py", line 139, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "c:\users\mcmartins\desktop\enrollment\venv\lib\site-packages\setuptools\dist.py", line 716, in fetch_build_eggs
        resolved_dists = pkg_resources.working_set.resolve(
      File "c:\users\mcmartins\desktop\enrollment\venv\lib\site-packages\pkg_resources\__init__.py", line 780, in resolve
        dist = best[req.key] = env.best_match(
      File "c:\users\mcmartins\desktop\enrollment\venv\lib\site-packages\pkg_resources\__init__.py", line 1065, in best_match
        return self.obtain(req, installer)
      File "c:\users\mcmartins\desktop\enrollment\venv\lib\site-packages\pkg_resources\__init__.py", line 1077, in obtain
        return installer(requirement)
      File "c:\users\mcmartins\desktop\enrollment\venv\lib\site-packages\setuptools\dist.py", line 786, in fetch_build_egg
        return cmd.easy_install(req)
      File "c:\users\mcmartins\desktop\enrollment\venv\lib\site-packages\setuptools\command\easy_install.py", line 679, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "c:\users\mcmartins\desktop\enrollment\venv\lib\site-packages\setuptools\command\easy_install.py", line 705, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "c:\users\mcmartins\desktop\enrollment\venv\lib\site-packages\setuptools\command\easy_install.py", line 890, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File "c:\users\mcmartins\desktop\enrollment\venv\lib\site-packages\setuptools\command\easy_install.py", line 1158, in build_and_install
        self.run_setup(setup_script, setup_base, args)
      File "c:\users\mcmartins\desktop\enrollment\venv\lib\site-packages\setuptools\command\easy_install.py", line 1146, in run_setup
        raise DistutilsError("Setup script exited with %s" % (v.args[0],))
    distutils.errors.DistutilsError: Setup script exited with error: SandboxViolation: mkdir('C:\\Users\\MCMART~1\\AppData\\Local\\Temp\\easy_install-pd3xglu5\\rednose-1.3.0\\build', 511) {}

    The package setup script has attempted to modify files on your system
    that are not within the EasyInstall build area, and has been aborted.

    This package cannot be safely installed by EasyInstall, and may not
    support alternate installation locations even if you run its setup
    script by hand.  Please inform the package's author and the EasyInstall
    maintainers to find out if a fix or workaround is available.

    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by brainox** [comment]
I have solved this issue by referring to previous suggested solution by @lafrech . Thank you
