### ISSUE TITLE
Cannot pip install flask-mongoengine in py3.6 (inside docker)

### ISSUE THREAD

**Issue by Ernestyj** [MongoEngine/flask-mongoengine#413]
Could anyone help on below pip install error (Python 3.6.2 |Continuum Analytics)?

The docker linux version is:
Linux version 3.10.0-1160.2.2.el7.x86_64 (mockbuild@kbuilder.bsys.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-44) (GCC) ) #1 SMP Tue Oct 20 16:53:08 UTC 2020

The pip install error is:
Collecting flask-mongoengine==0.9.2
  Downloading flask-mongoengine-0.9.2.tar.gz (112 kB)
    ERROR: Command errored out with exit status 1:
     command: /opt/conda/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-d9haeuek/flask-mongoengine/setup.py'"'"'; __file__='"'"'/tmp/pip-install-d9haeuek/flask-mongoengine/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-r24axjy6
         cwd: /tmp/pip-install-d9haeuek/flask-mongoengine/
    Complete output (101 lines):
    zip_safe flag not set; analyzing archive contents...
    test_files.__pycache__.new_tests.cpython-36: module references __path__
    __pycache__.rednose.cpython-36: module references __file__

    Installed /tmp/pip-install-d9haeuek/flask-mongoengine/.eggs/rednose-1.3.0-py3.6.egg
    Searching for nose
    Reading https://pypi.python.org/simple/nose/
    Downloading https://files.pythonhosted.org/packages/58/a5/0dc93c3ec33f4e281849523a5a913fa1eea9a3068acfa754d44d88107a44/nose-1.3.7.tar.gz#sha256=f1bffef9cbc82628f6e7d7b40d7e255aefaa1adb6a1b1d26c69a8b79e6208a98
    Best match: nose 1.3.7
    Processing nose-1.3.7.tar.gz
    Writing /tmp/easy_install-8_wqtzhe/nose-1.3.7/setup.cfg
    Running nose-1.3.7/setup.py -q bdist_egg --dist-dir /tmp/easy_install-8_wqtzhe/nose-1.3.7/egg-dist-tmp-3raytg_1
    no previously-included directories found matching 'doc/.build'
    creating /tmp/pip-install-d9haeuek/flask-mongoengine/.eggs/nose-1.3.7-py3.6.egg
    Extracting nose-1.3.7-py3.6.egg to /tmp/pip-install-d9haeuek/flask-mongoengine/.eggs

    Installed /tmp/pip-install-d9haeuek/flask-mongoengine/.eggs/nose-1.3.7-py3.6.egg
    Searching for coverage
    Reading https://pypi.python.org/simple/coverage/
    Downloading https://files.pythonhosted.org/packages/da/50/4c0c93ea67c8b42aa700cfbdedd64ea5ac5e7108ba14e3e744f57309304b/coverage-5.3.tar.gz#sha256=280baa8ec489c4f542f8940f9c4c2181f0306a8ee1a54eceba071a449fb870a0
    Best match: coverage 5.3
    Processing coverage-5.3.tar.gz
    Writing /tmp/easy_install-8jsrlbjw/coverage-5.3/setup.cfg
    Running coverage-5.3/setup.py -q bdist_egg --dist-dir /tmp/easy_install-8jsrlbjw/coverage-5.3/egg-dist-tmp-idrxqjm5
    /opt/conda/lib/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'long_description_content_type'
      warnings.warn(msg)
    /opt/conda/lib/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'project_urls'
      warnings.warn(msg)
    warning: no previously-included files found matching 'ci/*.token'
    no previously-included directories found matching 'doc/_build'
    no previously-included directories found matching 'doc/_spell'
    no previously-included directories found matching 'tests/eggsrc/build'
    warning: no previously-included files matching '*.py[co]' found anywhere in distribution
    creating /tmp/pip-install-d9haeuek/flask-mongoengine/.eggs/coverage-5.3-py3.6-linux-x86_64.egg
    Extracting coverage-5.3-py3.6-linux-x86_64.egg to /tmp/pip-install-d9haeuek/flask-mongoengine/.eggs

    Installed /tmp/pip-install-d9haeuek/flask-mongoengine/.eggs/coverage-5.3-py3.6-linux-x86_64.egg
    Searching for colorama
    Reading https://pypi.python.org/simple/colorama/
    Downloading https://files.pythonhosted.org/packages/1f/bb/5d3246097ab77fa083a61bd8d3d527b7ae063c7d8e8671b1cf8c4ec10cbe/colorama-0.4.4.tar.gz#sha256=5941b2b48a20143d2267e95b1c2a7603ce057ee39fd88e7329b0c292aa16869b
    Best match: colorama 0.4.4
    Processing colorama-0.4.4.tar.gz
    Writing /tmp/easy_install-717zw074/colorama-0.4.4/setup.cfg
    Running colorama-0.4.4/setup.py -q bdist_egg --dist-dir /tmp/easy_install-717zw074/colorama-0.4.4/egg-dist-tmp-cy6_xeb0
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/setuptools/sandbox.py", line 156, in save_modules
      File "/opt/conda/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/setuptools/sandbox.py", line 197, in setup_context
      File "/opt/conda/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/setuptools/sandbox.py", line 246, in run_setup
      File "/opt/conda/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/setuptools/sandbox.py", line 276, in run
      File "/opt/conda/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/setuptools/sandbox.py", line 245, in runner
      File "/opt/conda/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/setuptools/sandbox.py", line 47, in _execfile
      File "/tmp/easy_install-717zw074/colorama-0.4.4/setup.py", line 36, in <module>
        setup(
      File "/tmp/easy_install-717zw074/colorama-0.4.4/setup.py", line 19, in read_file

      File "/opt/conda/lib/python3.6/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 852: ordinal not in range(128)

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-d9haeuek/flask-mongoengine/setup.py", line 74, in <module>
        'Topic :: Software Development :: Libraries :: Python Modules'
      File "/opt/conda/lib/python3.6/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/opt/conda/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/setuptools/dist.py", line 315, in __init__
      File "/opt/conda/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/setuptools/dist.py", line 361, in fetch_build_eggs
      File "/opt/conda/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 851, in resolve
      File "/opt/conda/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 1123, in best_match
      File "/opt/conda/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 1135, in obtain
      File "/opt/conda/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/setuptools/dist.py", line 428, in fetch_build_egg
      File "/opt/conda/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/setuptools/command/easy_install.py", line 664, in easy_install
      File "/opt/conda/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/setuptools/command/easy_install.py", line 694, in install_item
      File "/opt/conda/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/setuptools/command/easy_install.py", line 875, in install_eggs
      File "/opt/conda/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/setuptools/command/easy_install.py", line 1114, in build_and_install
      File "/opt/conda/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/setuptools/command/easy_install.py", line 1100, in run_setup
      File "/opt/conda/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/setuptools/sandbox.py", line 249, in run_setup
      File "/opt/conda/lib/python3.6/contextlib.py", line 99, in __exit__
        self.gen.throw(type, value, traceback)
      File "/opt/conda/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/setuptools/sandbox.py", line 197, in setup_context
      File "/opt/conda/lib/python3.6/contextlib.py", line 99, in __exit__
        self.gen.throw(type, value, traceback)
      File "/opt/conda/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/setuptools/sandbox.py", line 168, in save_modules
      File "/opt/conda/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/setuptools/sandbox.py", line 143, in resume
      File "/opt/conda/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/_vendor/six.py", line 685, in reraise
        raise value.with_traceback(tb)
      File "/opt/conda/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/setuptools/sandbox.py", line 156, in save_modules
      File "/opt/conda/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/setuptools/sandbox.py", line 197, in setup_context
      File "/opt/conda/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/setuptools/sandbox.py", line 246, in run_setup
      File "/opt/conda/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/setuptools/sandbox.py", line 276, in run
      File "/opt/conda/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/setuptools/sandbox.py", line 245, in runner
      File "/opt/conda/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/setuptools/sandbox.py", line 47, in _execfile
      File "/tmp/easy_install-717zw074/colorama-0.4.4/setup.py", line 36, in <module>
        setup(
      File "/tmp/easy_install-717zw074/colorama-0.4.4/setup.py", line 19, in read_file

      File "/opt/conda/lib/python3.6/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 852: ordinal not in range(128)
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

CondaValueError: pip returned an error.

**Comment by insspb** [comment]
Hi @Ernestyj 
Please try last version from pip. Make a new issue if error persist. 
I just installed last version to docker with py  3.7
