### ISSUE TITLE
encoding error trying to install flask mongoengine in ubuntu xenial vm & python2.7

### ISSUE THREAD

**Issue by qre0ct** [MongoEngine/flask-mongoengine#426]
I keep getting the same error trying to get flask-mongoengine installed in Ubuntu xenial (python2.7). This used to work perfectly fine until roughly Feb/Mar 2020. 

```
vagrant@ubuntu-xenial:~$ sudo pip install flask-mongoengine
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
WARNING: The directory '/home/vagrant/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting flask-mongoengine
  Downloading flask-mongoengine-1.0.0.tar.gz (117 kB)
     |################################| 117 kB 2.0 MB/s
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python /usr/local/lib/python2.7/dist-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpsDsEsP
       cwd: /tmp/pip-install-qSP05Q/flask-mongoengine
  Complete output (18 lines):
  Traceback (most recent call last):
    File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
      main()
    File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/pep517/_in_process.py", line 114, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/usr/local/lib/python2.7/dist-packages/setuptools/build_meta.py", line 146, in get_requires_for_build_wheel
      return self._get_build_requires(config_settings, requirements=['wheel'])
    File "/usr/local/lib/python2.7/dist-packages/setuptools/build_meta.py", line 127, in _get_build_requires
      self.run_setup()
    File "/usr/local/lib/python2.7/dist-packages/setuptools/build_meta.py", line 243, in run_setup
      self).run_setup(setup_script=setup_script)
    File "/usr/local/lib/python2.7/dist-packages/setuptools/build_meta.py", line 142, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 12, in <module>
      long_description = open(doc_path, encoding="utf-8").read()
  TypeError: 'encoding' is an invalid keyword argument for this function
  ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python /usr/local/lib/python2.7/dist-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpsDsEsP Check the logs for full command output.
```

I have also tried `pip install wheel` and then `pip install flask-mongoengine` but it does not seem to solve the problem. Can someone please help me understand :

1. What's the problem here? Am I missing something?
2. What can I do to solve the issue?

**Comment by bagerard** [comment]
Sounds like you are trying to install latest version in a Python2.7 environment. 
Python 2.7 and 3.5 support got dropped with the 1.0.0 release of flask-mongoengine as they are end of life and so most major projects are dropping support for it.

If you need to stay on python 2.7 for whatever reason, you can pin the version of mongoengine & flask-mongoengine that you are using in the setup.py file. Otherwise just upgrade to recent Python3 version
